language: node_js
node_js:
  - '11.10.0'

cache:
  directories:
    - node_modules

before_install:
  - export TZ='Asia/Shanghai'

install: npm install
script: npm run build

deploy:
  provider: pages
  skip-cleanup: true
  github-token: $TOKEN
  local-dir: ./dist/
  target-branch: $BRANCH
  email: $UEMAIL
  name: $UNAME


branches:
  only:
    - master
