name: CI

on:
  push:
    branches:
    - master

jobs:
  build:
    runs-on: ubuntu-latest
  
    steps:
    - name: Deploy to GitHub Pages
      uses: JamesIves/github-pages-deploy-action@2.0.0
      env:
        ACCESS_TOKEN: ${{ secrets.ACCESS_TOKEN }}
        BRANCH: gh-pages
        FOLDER: ./dist/
        BUILD_SCRIPT: npm install && npm run-script build

